version: 0.1
   
phases:
  install:
    commands:
      - pip install Pygments
      - wget https://github.com/gohugoio/hugo/releases/download/v0.25.1/hugo_0.25.1_Linux-64bit.deb
      - sudo dpkg -i hugo*.deb
  build:
    commands:
      - echo "******** Building Hugo site ********"
      - hugo --buildFuture --buildDrafts --buildExpired -v
      - echo "******** Uploading to S3 ********"
      - aws s3 sync public/ s3://cloudbrackets.com