baseurl = "http://cloudbrackets.com"
languageCode = "en-gb"
title = "Cloud Brackets"
theme = "hpstr"
pluralizelisttitles = false
PygmentsCodeFences = true
Paginate = 5
disqusShortname = "cloudbrackets"

[params]
	subtitle = "A repository for Cloud Programming, musings, and nerdy fun"
	[params.author]
		name = "Steven Carnes"
		avatar = "/images/me.jpg"
		bio = "Sr Cloud Programmer, Nintendo Nerd, Cloud technologies enthusiast"
		github = "Stevio54"
	[params.image]
	  feature = "/images/clouds.jpg"

